FROM owncloud/ubuntu:18.10-arm32v7@sha256:0bac20d58af41982c747276e5f8183c2c058fe9e09408a0b56f52e5b683e4703

LABEL maintainer="ownCloud GmbH <devops@owncloud.com>" \
  org.opencontainers.image.title="ownCloud CI NodeJS" \
  org.opencontainers.image.vendor="ownCloud GmbH" \
  org.opencontainers.image.authors="ownCloud GmbH" \
  org.opencontainers.image.description="ownCloud CI NodeJS" \
  org.opencontainers.image.documentation="https://github.com/owncloud-ci/nodejs.git" \
  org.opencontainers.image.url="https://github.com/owncloud-ci/nodejs" \
  org.opencontainers.image.source="https://github.com/owncloud-ci/nodejs"

VOLUME ["/var/www/owncloud"]

RUN curl -s https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add - && \
  echo "deb https://deb.nodesource.com/node_14.x bionic main" | tee /etc/apt/sources.list.d/node.list

RUN apt-get update -y && \
  apt-get install -y nodejs git-core build-essential libpng16-16 && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN npm install -g yarn npx --force

COPY rootfs /
WORKDIR /var/www/owncloud
