FROM owncloud/ubuntu:20.04-arm32v7@sha256:3dc36e88b3ba3af99bc61144be2d86d6c54138742e0b29a044f4c7ddccf55d50

LABEL maintainer="ownCloud GmbH <devops@owncloud.com>" \
  org.opencontainers.image.title="ownCloud CI NodeJS" \
  org.opencontainers.image.vendor="ownCloud GmbH" \
  org.opencontainers.image.authors="ownCloud GmbH" \
  org.opencontainers.image.description="ownCloud CI NodeJS" \
  org.opencontainers.image.documentation="https://github.com/owncloud-ci/nodejs.git" \
  org.opencontainers.image.url="https://github.com/owncloud-ci/nodejs" \
  org.opencontainers.image.source="https://github.com/owncloud-ci/nodejs"

VOLUME ["/var/www/owncloud"]

RUN apt-get update -y && \
  apt-get install -y git-core build-essential libpng16-16 lsb-release && \
  curl -s https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add - && \
  echo "deb https://deb.nodesource.com/node_12.x $(lsb_release -sc) main" | tee /etc/apt/sources.list.d/node.list && \
  apt-get update -y && \
  apt-get install -y nodejs && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN npm install -g yarn npx --force

COPY rootfs /
WORKDIR /var/www/owncloud
