FROM owncloud/ubuntu:18.10-arm64v8@sha256:d59a37112df13af61326aa67a83a8b777b84a6e52a487691109a21414884c6fa

LABEL maintainer="ownCloud GmbH <devops@owncloud.com>" \
  org.opencontainers.image.title="ownCloud CI NodeJS" \
  org.opencontainers.image.vendor="ownCloud GmbH" \
  org.opencontainers.image.authors="ownCloud GmbH" \
  org.opencontainers.image.description="ownCloud CI NodeJS" \
  org.opencontainers.image.documentation="https://github.com/owncloud-ci/nodejs.git" \
  org.opencontainers.image.url="https://github.com/owncloud-ci/nodejs" \
  org.opencontainers.image.source="https://github.com/owncloud-ci/nodejs"

VOLUME ["/var/www/owncloud"]

RUN curl -s https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add - && \
  echo "deb https://deb.nodesource.com/node_12.x bionic main" | tee /etc/apt/sources.list.d/node.list

RUN apt-get update -y && \
  apt-get install -y nodejs git-core build-essential libpng16-16 && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN npm install -g yarn npx --force

COPY rootfs /
WORKDIR /var/www/owncloud
