FROM owncloud/ubuntu:22.04@sha256:c4d94933598c0d45080c583982d94a8a17b3e60e2038efd8beb75b349b8af1c1

LABEL maintainer="ownCloud GmbH <devops@owncloud.com>" \
  org.opencontainers.image.title="ownCloud CI NodeJS" \
  org.opencontainers.image.vendor="ownCloud GmbH" \
  org.opencontainers.image.authors="ownCloud GmbH" \
  org.opencontainers.image.description="ownCloud CI NodeJS" \
  org.opencontainers.image.documentation="https://github.com/owncloud-ci/nodejs.git" \
  org.opencontainers.image.url="https://github.com/owncloud-ci/nodejs" \
  org.opencontainers.image.source="https://github.com/owncloud-ci/nodejs"

ARG RETRY_VERSION

# renovate: datasource=github-releases depName=owncloud-ci/retry
ENV RETRY_VERSION="${RETRY_VERSION:-v2.0.0}"
# renovate: datasource=npm depName=pnpm
ENV PNPM_VERSION="${PNPM_VERSION:-10.11.0}"

VOLUME ["/var/www/owncloud"]

RUN apt-get update -y && \
  apt-get install -y gettext file git-core build-essential libfontconfig libpng16-16 lsb-release firefox && \
  curl -SsfL -o /usr/local/bin/retry "https://github.com/owncloud-ci/retry/releases/download/v${RETRY_VERSION##v}/retry" && \
  chmod 755 /usr/local/bin/retry && \
  curl -s https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add - && \
  curl -fsSL https://deb.nodesource.com/setup_22.x | bash - && \
  apt-get update -y && \
  apt-get install -y nodejs && \
  if [ "$(uname -m)" = "x86_64" ]; then \
    wget -q -P /tmp https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb && \
    apt install -y /tmp/google-chrome-stable_current_amd64.deb; \
  fi && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN npm install --silent -g yarn npx "pnpm@$PNPM_VERSION" --force

COPY rootfs /
WORKDIR /var/www/owncloud
